import Router from "koa-router";
import swaggerDocument from "../swagger/swagger.json"; // Assuming swagger.json is generated by tsoa

const router = new Router();

router.get("/docs", async (ctx) => {
  ctx.body = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Bank APP - API Documentation</title>
        <link rel="stylesheet" type="text/css" href="/swagger-ui.css">
        <script src="/swagger-ui-bundle.js"></script>
        <script src="/swagger-ui-standalone-preset.js"></script>
      </head>
      <body>
        <div class="swagger-ui"></div>
        <script>
          const ui = SwaggerUIBundle({
            url: '/swagger.json', // URL to your swagger.json file
            dom_id: '.swagger-ui',
            presets: [
              SwaggerUIBundle.presets.apis,
              SwaggerUIStandalonePreset
            ],
            layout: "StandaloneLayout"
          });
        </script>
      </body>
      </html>`;
});

// Serve Swagger JSON
router.get("/swagger.json", async (ctx) => {
  ctx.body = swaggerDocument;
});

export default router;
